CREATE TABLE IF NOT EXISTS state(k TEXT PRIMARY KEY,v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS checkins(ticket TEXT PRIMARY KEY,ts BIGINT,staff TEXT);
CREATE TABLE IF NOT EXISTS leads(id BIGSERIAL PRIMARY KEY,kind TEXT,status TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS registrations(email TEXT PRIMARY KEY,status TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS bookings(email TEXT,session_id TEXT,status TEXT,ts BIGINT,PRIMARY KEY(email,session_id));
CREATE TABLE IF NOT EXISTS questions(id BIGSERIAL PRIMARY KEY,text TEXT,status TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS placements(id BIGSERIAL PRIMARY KEY,name TEXT,status TEXT,leads INTEGER DEFAULT 0,ts BIGINT);
CREATE TABLE IF NOT EXISTS deliverables(id TEXT PRIMARY KEY,label TEXT,status TEXT,evidence TEXT,updated BIGINT);
CREATE TABLE IF NOT EXISTS attendee_profiles(email TEXT PRIMARY KEY,intent TEXT,interests TEXT,networking INTEGER DEFAULT 0,visibility TEXT DEFAULT 'event_only',updated BIGINT);
CREATE TABLE IF NOT EXISTS meetings(id BIGSERIAL PRIMARY KEY,requester TEXT,target TEXT,slot TEXT,place TEXT,status TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS session_feedback(id BIGSERIAL PRIMARY KEY,email TEXT,session_id TEXT,rating INTEGER,useful INTEGER,comment TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS takeaways(id BIGSERIAL PRIMARY KEY,email TEXT,session_id TEXT,note TEXT,source TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS product_interests(id BIGSERIAL PRIMARY KEY,email TEXT,track TEXT,context TEXT,consent_version TEXT,status TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS followups(id BIGSERIAL PRIMARY KEY,email TEXT,day INTEGER,track TEXT,status TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS program_items(id TEXT PRIMARY KEY,start TEXT,end TEXT,venue TEXT,track TEXT,format TEXT,title TEXT,audience TEXT,capacity INTEGER,stream INTEGER,replay INTEGER,partner TEXT);
CREATE TABLE IF NOT EXISTS activity_bookings(email TEXT,item_id TEXT,status TEXT,ts BIGINT,PRIMARY KEY(email,item_id));
CREATE TABLE IF NOT EXISTS challenges(email TEXT,challenge_id TEXT,status TEXT,days_required INTEGER,started BIGINT,verified INTEGER,reward TEXT,PRIMARY KEY(email,challenge_id));
CREATE TABLE IF NOT EXISTS challenge_actions(email TEXT,challenge_id TEXT,action_id TEXT,label TEXT,status TEXT,ts BIGINT,PRIMARY KEY(email,challenge_id,action_id));
CREATE TABLE IF NOT EXISTS speakers(id TEXT PRIMARY KEY,name TEXT,role TEXT,org TEXT,bio TEXT,topics TEXT,kind TEXT);
CREATE TABLE IF NOT EXISTS partners(id TEXT PRIMARY KEY,name TEXT,category TEXT,description TEXT,status TEXT);
CREATE TABLE IF NOT EXISTS product_catalog(id TEXT PRIMARY KEY,name TEXT,inn TEXT,company TEXT,theme TEXT,kind TEXT,summary TEXT,source_label TEXT,source_url TEXT,disclosure TEXT);
CREATE TABLE IF NOT EXISTS content_catalog(id TEXT PRIMARY KEY,kind TEXT,theme TEXT,title TEXT,dek TEXT,duration TEXT,author TEXT,reviewer TEXT,partner TEXT,status TEXT);
CREATE TABLE IF NOT EXISTS partner_packages(id TEXT PRIMARY KEY,name TEXT,tier TEXT,summary TEXT,deliverables TEXT,measurement TEXT,disclosure TEXT);
CREATE TABLE IF NOT EXISTS studio_episodes(id TEXT PRIMARY KEY,topic TEXT,title TEXT,dek TEXT,duration TEXT,speaker_id TEXT,content_id TEXT,item_id TEXT,thread_id TEXT,track_id TEXT,status TEXT);
CREATE TABLE IF NOT EXISTS community_threads(id TEXT PRIMARY KEY,topic TEXT,title TEXT,summary TEXT,moderator TEXT,status TEXT,related_item TEXT);
CREATE TABLE IF NOT EXISTS community_posts(id BIGSERIAL PRIMARY KEY,thread_id TEXT,email TEXT,body TEXT,status TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS topic_subscriptions(email TEXT,topic TEXT,status TEXT,ts BIGINT,PRIMARY KEY(email,topic));
CREATE TABLE IF NOT EXISTS expert_follows(email TEXT,speaker_id TEXT,status TEXT,ts BIGINT,PRIMARY KEY(email,speaker_id));
CREATE TABLE IF NOT EXISTS learning_tracks(id TEXT PRIMARY KEY,topic TEXT,title TEXT,summary TEXT,duration_days INTEGER,level TEXT);
CREATE TABLE IF NOT EXISTS learning_steps(track_id TEXT,step_no INTEGER,kind TEXT,ref_id TEXT,title TEXT,PRIMARY KEY(track_id,step_no));
CREATE TABLE IF NOT EXISTS learning_enrollments(email TEXT,track_id TEXT,status TEXT,current_step INTEGER DEFAULT 0,started BIGINT,updated BIGINT,PRIMARY KEY(email,track_id));
CREATE TABLE IF NOT EXISTS session_speakers(item_id TEXT,speaker_id TEXT,PRIMARY KEY(item_id,speaker_id));
CREATE TABLE IF NOT EXISTS appointment_slots(id TEXT PRIMARY KEY,item_id TEXT,start TEXT,end TEXT,capacity INTEGER,partner_id TEXT);
CREATE TABLE IF NOT EXISTS appointment_bookings(email TEXT,slot_id TEXT,status TEXT,ts BIGINT,PRIMARY KEY(email,slot_id));
CREATE TABLE IF NOT EXISTS replay_chapters(id TEXT PRIMARY KEY,item_id TEXT,offset_sec INTEGER,title TEXT,kind TEXT);
CREATE TABLE IF NOT EXISTS mutual_meetings(id BIGSERIAL PRIMARY KEY,requester TEXT,target_email TEXT,target_name TEXT,slot TEXT,place TEXT,status TEXT,requester_ok INTEGER DEFAULT 1,target_ok INTEGER DEFAULT 0,ts BIGINT);
CREATE TABLE IF NOT EXISTS venue_state(venue TEXT PRIMARY KEY,capacity INTEGER,occupied INTEGER,status TEXT,next_change TEXT,updated BIGINT);
CREATE TABLE IF NOT EXISTS incidents(id BIGSERIAL PRIMARY KEY,venue TEXT,severity TEXT,title TEXT,status TEXT,recovery TEXT,ts BIGINT,resolved BIGINT);
CREATE TABLE IF NOT EXISTS stream_state(item_id TEXT PRIMARY KEY,status TEXT,health TEXT,delay_sec INTEGER,updated BIGINT);
CREATE TABLE IF NOT EXISTS appointment_history(id BIGSERIAL PRIMARY KEY,email TEXT,slot_id TEXT,action TEXT,from_slot TEXT,to_slot TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS session_attendance(email TEXT,item_id TEXT,status TEXT,checkin_ts BIGINT,checkout_ts BIGINT,source TEXT,PRIMARY KEY(email,item_id));
CREATE TABLE IF NOT EXISTS partner_engagement(id BIGSERIAL PRIMARY KEY,email TEXT,partner TEXT,kind TEXT,ref_id TEXT,consent INTEGER DEFAULT 0,ts BIGINT);
CREATE TABLE IF NOT EXISTS staff_assignments(id BIGSERIAL PRIMARY KEY,staff_name TEXT,role TEXT,venue TEXT,shift_start TEXT,shift_end TEXT,status TEXT,updated BIGINT);
CREATE TABLE IF NOT EXISTS speaker_readiness(speaker_id TEXT,item_id TEXT,status TEXT,checkin INTEGER DEFAULT 0,briefed INTEGER DEFAULT 0,mic INTEGER DEFAULT 0,slides INTEGER DEFAULT 0,updated BIGINT,PRIMARY KEY(speaker_id,item_id));
CREATE TABLE IF NOT EXISTS ops_broadcasts(id BIGSERIAL PRIMARY KEY,audience TEXT,venue TEXT,title TEXT,body TEXT,status TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS passport(email TEXT PRIMARY KEY,content INTEGER DEFAULT 0,event INTEGER DEFAULT 0,network INTEGER DEFAULT 0,partner INTEGER DEFAULT 0,updated BIGINT);
CREATE TABLE IF NOT EXISTS journeys(email TEXT PRIMARY KEY,attended INTEGER DEFAULT 0,replay INTEGER DEFAULT 0,club INTEGER DEFAULT 0,updated BIGINT);
CREATE TABLE IF NOT EXISTS notifications(id BIGSERIAL PRIMARY KEY,email TEXT,kind TEXT,title TEXT,body TEXT,seen INTEGER DEFAULT 0,ts BIGINT);
CREATE TABLE IF NOT EXISTS direct_messages(id BIGSERIAL PRIMARY KEY,sender TEXT,recipient TEXT,context TEXT,body TEXT,status TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS events(id BIGSERIAL PRIMARY KEY,kind TEXT,actor TEXT,payload TEXT,ts BIGINT);
CREATE TABLE IF NOT EXISTS cms(id TEXT PRIMARY KEY,status TEXT,version INTEGER,updated BIGINT);
CREATE TABLE IF NOT EXISTS auth_sessions(token_hash TEXT PRIMARY KEY,email TEXT NOT NULL,role TEXT NOT NULL,name TEXT NOT NULL,created_at BIGINT NOT NULL,expires_at BIGINT NOT NULL,revoked_at BIGINT);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_email ON auth_sessions(email);
CREATE INDEX IF NOT EXISTS idx_notifications_email_ts ON notifications(email,ts);
CREATE INDEX IF NOT EXISTS idx_direct_messages_parties_ts ON direct_messages(sender,recipient,ts);
